name: PlatformIO CI
on: [push]
jobs:
  build:
    runs-on: self-hosted
    container:
      image: ghcr.io/petrows/platformio:v3
      options: -u 2025:2025
    strategy:
      matrix:
        model: ['rgb', 'retro']
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - name: Build firmware
        run: |
            echo "::group::pio ci"
            # See Dockerfile for static environment
            export CI=true
            cd firmware/tasmota
            # Copy config overrides
            cp ../user_config_override.h tasmota/
            # Copy HW version config
            cp ../user_config_hw_${{ matrix.model }}.h tasmota/user_config_hw.h
            # Build firmware
            platformio run -e tasmota32
            # Pack result firmware.bin
            cp .pio/build/tasmota32/firmware.bin galoped-dekad-firmware-${{ matrix.model }}.bin
            tar -czf galoped-dekad-firmware-${{ matrix.model }}.tar.gz galoped-dekad-firmware-${{ matrix.model }}.bin
            echo "::endgroup::"
      - name: Archive firmware file
        uses: actions/upload-artifact@v4
        with:
          name: galoped-dekad-firmware
          path: galoped-dekad-firmware-${{ matrix.model }}.tar.gz
