name: PlatformIO CI
on: [push]
jobs:
  build:
    runs-on: self-hosted
    container:
      image: ghcr.io/petrows/platformio:v3
      options: -u 2025:2025
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - name: Build PlatformIO examples
        run: |
            echo "::group::pio ci"
            # See Dockerfile for static environment
            export CI=true
            ls -la ~/.platformio/.cache || true
            cd firmware/tasmota
            # Copy config overrides
            cp ../user_config_override.h tasmota/
            platformio run -e tasmota32
            ls -la ~/.platformio/.cache || true
            echo "::endgroup::"
