name: PlatformIO CI
on:
  push:
    paths:
      - 'firmware/**'
    branches:
      - master
  pull_request:
    paths:
      - 'firmware/**'
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    container:
      image: ghcr.io/petrows/platformio:v4
      options: -u 2025:2025
    strategy:
      matrix:
        model: ['rgb', 'retro']
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - name: Build firmware
        run: |
            echo "::group::pio ci"
            # See Dockerfile for static environment
            export CI=true
            ./bin/build.sh ${{ matrix.model }}
            echo "::endgroup::"
      - name: Archive firmware file
        uses: actions/upload-artifact@v4
        with:
          name: galoped-dekad-firmware
          path: firmware/galoped-dekad-firmware-${{ matrix.model }}.tar.gz
